version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: node-app
    ports:
      - '3000:3000'
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
    depends_on:
      - mongo

volumes:
  mongo-data:
